name: IA Size Calculator

on:
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Search Query (e.g., uploader:jscott@archive.org)'
        required: true
        default: 'uploader:example@example.com'

jobs:
  calculate-size:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v 6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v 6.2.0
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v 5.0.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-calc-${{ hashFiles('.github/workflows/acc_calc.yml') }}
          restore-keys: |
            ${{ runner.os }}-calc-

      - name: Install Dependencies
        run: |
          pip install internetarchive

      - name: Run Calculation
        env:
          INPUT_QUERY: ${{ inputs.search_query }}
        run: python iacalc.py
