name: IA Size Calculator

on:
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Search Query (e.g., uploader:jscott@archive.org)'
        required: true
        default: 'uploader:example@example.com'

jobs:
  calculate-size:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v 6.0.2

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v 6.2.0
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@565629816435f6c0b50676926c9b05c254113c0c # v 5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-calc-${{ hashFiles('.github/workflows/acc_calc.yml') }}
          restore-keys: |
            ${{ runner.os }}-calc-

      - name: Install Dependencies
        run: |
          pip install internetarchive

      - name: Run Calculation
        env:
          INPUT_QUERY: ${{ inputs.search_query }}
        run: python iacalc.py
