name: Download Instagram Account

on:
  workflow_dispatch:
    inputs:
      instagram_username:
        description: 'Instagram username to download from'
        required: true

jobs:
  download-instagram:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Instaloader
      run: |
        python -m pip install --upgrade pip
        pip install instaloader

    - name: Create download directory
      run: mkdir download

    - name: Download Instagram media
      env:
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      run: |
        cd download
        instaloader --login "$IG_USERNAME" --password "$IG_PASSWORD" --dirname-pattern="{target}" --fast-update "${{ github.event.inputs.instagram_username }}"

    - name: Zip the downloaded media
      run: |
        cd download
        zip -r ../instagram-media.zip .

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: instagram-media
        path: instagram-media.zip
