name: Firmware Extract and Commit

on:
  workflow_dispatch:

jobs:
  extractfirmware:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ipsw tool
        run: brew install blacktop/tap/ipsw

      - name: Download firmware 22F76 only
        run: |
          mkdir -p firmware
          cd firmware
          # download only build 22F76 for iPhone17,2
          ipsw download ipsw \
            --device iPhone17,2 \
            --build 22F76 \
            --confirm
          echo "FIRMWARE_PATH=$(ls *.ipsw)" >> $GITHUB_ENV

      - name: Extract firmware
        run: |
          cd firmware
          mkdir -p extracted
          ipsw extract "$FIRMWARE_PATH" -d extracted

      - name: Upload firmware as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-firmware-extracted
          path: firmware/extracted
          retention-days: 90

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit the extracted files
        run: |
          rsync -a firmware/extracted/ ./
          git add .
          git commit -m "Add extracted firmware files" || echo "Nothing to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
