name: Search for Text in a File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the file to search'
        required: true
        type: string
      search_text:
        description: 'Text to search in the file'
        required: true
        type: string

jobs:
  search-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Search text in file
        run: |
          FILE="${{ github.event.inputs.filename }}"
          TEXT="${{ github.event.inputs.search_text }}"

          if [[ ! -f "$FILE" ]]; then
            echo "File '$FILE' not found you hooligian"
            exit 1
          fi

          if grep -q "$TEXT" "$FILE"; then
            echo "Text '$TEXT' found in file '$FILE'"
          else
            echo "Text '$TEXT' not found in file '$FILE'"
            exit 1
          fi
